name: YouTube Shorts Generator

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Video URL'
        required: true
        type: string

jobs:
  generate_shorts:
    runs-on: macos-latest
    env:
      ELEVENLABS_API_KEY: sk_f165fcd0dc8fc1add50393e50d8501df185561420ed92002
      GEMINI_API_KEY: AIzaSyBaHx9w6G6Ffz2Wq37wyEZYVi6b4REN8GQ
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          brew install ffmpeg jq

      - name: Make working directory
        run: |
          mkdir -p shorts_workflow
          
      - name: Make all scripts executable
        run: chmod +x demo.sh shorts_workflow/*.sh


      - name: Run demo.sh with YouTube URL
        run: |
          chmod +x demo.sh
          ./demo.sh "${{ github.event.inputs.youtube_url }}"

      - name: Upload generated content
        uses: actions/upload-artifact@v4
        with:
          name: shorts_outputs
          path: shorts_workflow
